/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlisinhvien;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLi extends javax.swing.JFrame implements QuanLiThongTin{

    /**
     * Creates new form QuanLi
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel26 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        NamHoc = new javax.swing.JTextField();
        MSSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HoVaTen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TinChi = new javax.swing.JRadioButton();
        ChuongTrinh = new javax.swing.JRadioButton();
        TinChiDangKi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SoHocPhan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuanliInhVien = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Warning = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MotTinChi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        MotHocPhan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        HeSo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        PhiQuanLi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        TinhTinChi = new javax.swing.JButton();
        CanEdit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        HoTenTimKiem = new javax.swing.JTextField();
        MSSVTimKiem = new javax.swing.JTextField();
        SoTinChiTimKiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        QuanliSinhVien1 = new javax.swing.JTable();
        LookUp = new javax.swing.JButton();
        ErrorTimKiem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TgianThongKe = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        SoLuongSinhVienChuongTrinh = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SoLuongSinhVienTinChi = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        SoLuongSinhVien = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        HocPhi = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        HocPhiTheoTinChi = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        HocPhiTheoChuongTrinhMau = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        errThongKe = new javax.swing.JLabel();

        jLabel26.setText("jLabel26");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Năm Học");

        jLabel3.setText("MSSV");

        jLabel1.setText("Họ Và Tên");

        jLabel5.setText("Hình Thức đăng kí học");

        TinChi.setText("Tín Chỉ");
        TinChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinChiActionPerformed(evt);
            }
        });

        ChuongTrinh.setText("Chương Trình Học");
        ChuongTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuongTrinhActionPerformed(evt);
            }
        });

        TinChiDangKi.setEditable(false);

        jLabel4.setText("Tín chỉ đăng kí / năm");

        jLabel6.setText("Số học phần");

        SoHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoHocPhanActionPerformed(evt);
            }
        });

        QuanliInhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ Và tên", "MSSV", "Hình thức học", "Số học phần", "Tín Chỉ", "Năm Học", "Học Phí"
            }
        ));
        QuanliInhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanliInhVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(QuanliInhVien);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Warning.setForeground(new java.awt.Color(255, 0, 51));

        jLabel11.setText("Học Phí: ");

        jLabel12.setText("1 Tín Chỉ: ");

        MotTinChi.setEditable(false);
        MotTinChi.setText("250000");

        jLabel13.setText("1 Học Phần: ");

        MotHocPhan.setEditable(false);
        MotHocPhan.setText("625000");

        jLabel14.setText("Hệ số tín chỉ/Học Phần:");

        HeSo.setEditable(false);
        HeSo.setText("3");

        jLabel15.setText("Phí Quản Lí: ");

        PhiQuanLi.setEditable(false);
        PhiQuanLi.setText("1000000");

        jLabel16.setText("VNĐ");

        jLabel17.setText("VNĐ");

        jLabel18.setText("VNĐ");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Edit1.setText("Edit");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });

        TinhTinChi.setText("Tính Tín chỉ");
        TinhTinChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhTinChiActionPerformed(evt);
            }
        });

        CanEdit.setText("        ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Edit)
                .addGap(254, 254, 254)
                .addComponent(Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit)
                .addGap(53, 53, 53))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(TinChiDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TinhTinChi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MotTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MotHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HeSo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(SoHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhiQuanLi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TinChi)
                                        .addGap(42, 42, 42)
                                        .addComponent(ChuongTrinh))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(NamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(CanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(Edit1)
                .addGap(33, 33, 33)
                .addComponent(update)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(MSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(NamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TinChi)
                    .addComponent(ChuongTrinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(SoHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(TinChiDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TinhTinChi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(MotTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(MotHocPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(HeSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(PhiQuanLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(1, 1, 1)
                .addComponent(CanEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Edit)
                    .addComponent(Delete))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thông Tin", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tìm Kiếm");

        jLabel8.setText("Họ Tên");

        jLabel9.setText("MSSV");

        jLabel10.setText("Số Tín Chỉ");

        SoTinChiTimKiem.setText("0");

        QuanliSinhVien1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ Và tên", "MSSV", "Hình thức học", "Số học phần", "Tín Chỉ", "Năm Học", "Học Phí"
            }
        ));
        QuanliSinhVien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuanliSinhVien1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(QuanliSinhVien1);

        LookUp.setText("Tìm Kiếm");
        LookUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LookUpActionPerformed(evt);
            }
        });

        ErrorTimKiem.setForeground(new java.awt.Color(255, 0, 0));
        ErrorTimKiem.setText("      ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MSSVTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoTinChiTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTenTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(LookUp))
                    .addComponent(ErrorTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(HoTenTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(MSSVTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(SoTinChiTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(LookUp)
                .addGap(18, 18, 18)
                .addComponent(ErrorTimKiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tìm Kiếm", jPanel2);

        jLabel19.setText("Thời Gian Thông Kê:");

        ThongKe.setText("Thống Kê");
        ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeActionPerformed(evt);
            }
        });

        jLabel20.setText("+ Số lượng sinh viên học theo tín chỉ: ");

        jLabel21.setText("Sinh Viên");

        jLabel22.setText("+ Số lượng sinh viên học theo chương trình mãu:");

        SoLuongSinhVienChuongTrinh.setText("..............");

        jLabel24.setText("Sinh Viên");

        SoLuongSinhVienTinChi.setText("..............");

        jLabel23.setText("Học phí thu được: ");

        jLabel25.setText("Số Lượng Sinh Viên: ");

        SoLuongSinhVien.setText("..............");

        jLabel27.setText("Sinh Viên");

        HocPhi.setText("..............");

        jLabel28.setText("VNĐ");

        jLabel29.setText("+ Theo Tín Chỉ");

        HocPhiTheoTinChi.setText("..............");

        jLabel30.setText("VNĐ");

        jLabel31.setText("+ Theo Chương Trình Mẫu:");

        HocPhiTheoChuongTrinhMau.setText("..............");

        jLabel32.setText("VNĐ");

        errThongKe.setForeground(new java.awt.Color(255, 0, 0));
        errThongKe.setText("   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(55, 55, 55))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addGap(30, 30, 30)
                                        .addComponent(SoLuongSinhVien)
                                        .addGap(37, 37, 37)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(TgianThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)
                                        .addComponent(ThongKe)
                                        .addGap(18, 18, 18)
                                        .addComponent(errThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(SoLuongSinhVienTinChi)
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel21))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel22))
                                        .addGap(18, 18, 18)
                                        .addComponent(SoLuongSinhVienChuongTrinh)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(36, 36, 36)
                                .addComponent(HocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(HocPhiTheoChuongTrinhMau, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel32))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(HocPhiTheoTinChi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel30)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TgianThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongKe)
                    .addComponent(jLabel19)
                    .addComponent(errThongKe))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(SoLuongSinhVien)
                    .addComponent(jLabel27))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(SoLuongSinhVienTinChi))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(SoLuongSinhVienChuongTrinh)
                    .addComponent(jLabel24))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(HocPhi)
                    .addComponent(jLabel28))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(HocPhiTheoTinChi)
                    .addComponent(jLabel30))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(HocPhiTheoChuongTrinhMau)
                    .addComponent(jLabel32))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống Kê", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Thuoc tinh
    private List<StudentInf> dssv;
    
    // Phuong thuc
    // Ham khoi tao
    public QuanLi() {
        initComponents();
        dssv = new ArrayList(10);
    }
    
    // Ham them sinh vien vao danh sach
    @Override
    public void themSV(StudentInf sv) {
        dssv.add(sv);
    }
    
    //Ham tinh hoc phi theo tin chi
    @Override
    public double HocPhiTinChi(int tinchi){
        int phiTinChi = Integer.parseInt(MotTinChi.getText()); 
        return tinchi*phiTinChi;
    }
    
    //Ham Tinh hoc phi theo chuong trinh hoc
    @Override
    public double HocPhiChuongTrinhMau(int hocphan){
        int phiQuanLi = Integer.parseInt(PhiQuanLi.getText());
        int phiHocPhan = Integer.parseInt(MotHocPhan.getText());
        return hocphan*phiHocPhan + phiQuanLi;
    }
    
    //Ham chon tinh thuc hoc theo tin chi
    private void TinChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinChiActionPerformed
        if(TinChi.isSelected()){
            ChuongTrinh.setSelected(false);
        }
    }//GEN-LAST:event_TinChiActionPerformed
    
    //Ham chon tinh thuc hoc theo chuong trinh hoc
    private void ChuongTrinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuongTrinhActionPerformed
        if(ChuongTrinh.isSelected()){
            TinChi.setSelected(false);
        }
    }//GEN-LAST:event_ChuongTrinhActionPerformed
    
    //Ham lay gia tri da chon
    private void QuanliInhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanliInhVienMouseClicked
        DefaultTableModel QuanLiSinhVien = (DefaultTableModel) QuanliInhVien.getModel();
        int i= QuanliInhVien.getSelectedRow();

        HoVaTen.setText(QuanLiSinhVien.getValueAt(i, 0).toString());
        MSSV.setText(QuanLiSinhVien.getValueAt(i, 1).toString());
        NamHoc.setText(QuanLiSinhVien.getValueAt(i, 5).toString());
        TinChiDangKi.setText(String.valueOf(QuanLiSinhVien.getValueAt(i, 4)));
        SoHocPhan.setText(String.valueOf(QuanLiSinhVien.getValueAt(i, 3)));
    }//GEN-LAST:event_QuanliInhVienMouseClicked
    
    //Ham xoa gia tri da chon
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel QuanLiSinhVien = (DefaultTableModel) QuanliInhVien.getModel();
        int i = QuanliInhVien.getSelectedRow();
        if(QuanliInhVien.getSelectedRowCount()==1){
            QuanLiSinhVien.removeRow(i);
            dssv.remove(i);
            JOptionPane.showMessageDialog(this,"Data is deleted");
        } else{
            if(QuanliInhVien.getRowCount()==0){JOptionPane.showMessageDialog(this,"Table is empty");}
            else {
                JOptionPane.showMessageDialog(this,"Please select signle row for delete");
            }
        }
        hienThiDanhSach();
    }//GEN-LAST:event_DeleteActionPerformed
    
    //Ham chinh sua gia tri da chon
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        DefaultTableModel QuanLiSinhVien = (DefaultTableModel) QuanliInhVien.getModel();
        int i= QuanliInhVien.getSelectedRow();
        StudentInf sv;
        if(i>=0){
            if(QuanLiSinhVien.getValueAt(i, 2).equals("Tín Chỉ")){
                QuanLiSinhVien.setValueAt(HoVaTen.getText(), i, 0);
                QuanLiSinhVien.setValueAt(MSSV.getText(), i, 1);
                QuanLiSinhVien.setValueAt(Integer.parseInt(SoHocPhan.getText()), i, 3);
                QuanLiSinhVien.setValueAt(Integer.parseInt(TinChiDangKi.getText()), i, 4);
                QuanLiSinhVien.setValueAt(NamHoc.getText(), i, 5);
                QuanLiSinhVien.setValueAt(HocPhiTinChi(Integer.parseInt(TinChiDangKi.getText())), i, 6);
                sv = new StudentInf(HoVaTen.getText(),MSSV.getText(),Integer.parseInt(TinChiDangKi.getText()),Integer.parseInt(SoHocPhan.getText()),NamHoc.getText(),"Tín Chỉ");
                dssv.set(i, sv);
                HoVaTen.setText("");
                MSSV.setText("");
                NamHoc.setText("");
                TinChiDangKi.setText("");
                SoHocPhan.setText("");

            } else if (QuanLiSinhVien.getValueAt(i, 2).equals("Chương Trình Mẫu")){
                QuanLiSinhVien.setValueAt(HoVaTen.getText(), i, 0);
                QuanLiSinhVien.setValueAt(MSSV.getText(), i, 1);
                QuanLiSinhVien.setValueAt(Integer.parseInt(SoHocPhan.getText()), i, 3);
                QuanLiSinhVien.setValueAt(Integer.parseInt(TinChiDangKi.getText()), i, 4);
                QuanLiSinhVien.setValueAt(NamHoc.getText(), i, 5);
                QuanLiSinhVien.setValueAt(HocPhiChuongTrinhMau(Integer.parseInt(SoHocPhan.getText())), i, 6);
                sv = new StudentInf(HoVaTen.getText(),MSSV.getText(),Integer.parseInt(TinChiDangKi.getText()),Integer.parseInt(SoHocPhan.getText()),NamHoc.getText(),"Chương Trình Mẫu");
                dssv.set(i, sv);
                HoVaTen.setText("");
                MSSV.setText("");
                NamHoc.setText("");
                TinChiDangKi.setText("");
                SoHocPhan.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Update Error");
        }
        hienThiDanhSach();
    }//GEN-LAST:event_EditActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        DefaultTableModel QuanLiSinhVien = (DefaultTableModel) QuanliInhVien.getModel();
        String hovaten = HoVaTen.getText();
        String mssv = MSSV.getText();
        String namHoc = NamHoc.getText();
        int tinChi = Integer.parseInt(TinChiDangKi.getText());
        int soHocPhan = Integer.parseInt(SoHocPhan.getText());
        StudentInf sv ;
        if(TinChi.isSelected()){
            QuanLiSinhVien.addRow(new Object[]{hovaten,mssv,"Tín Chỉ",soHocPhan,tinChi,namHoc,HocPhiTinChi(tinChi)});
            sv = new StudentInf(hovaten,mssv,tinChi,soHocPhan,namHoc,"Tín Chỉ");
            // Them sv vao danh sach
            themSV(sv);
            HoVaTen.setText("");
            MSSV.setText("");
            NamHoc.setText("");
            TinChiDangKi.setText("");
            Warning.setText("");
            SoHocPhan.setText("");
            TinChi.setSelected(false);
        }
        else if(ChuongTrinh.isSelected()){
            QuanLiSinhVien.addRow(new Object[]{hovaten,mssv,"Chương Trình Mẫu",soHocPhan,tinChi,namHoc,HocPhiChuongTrinhMau(soHocPhan)});
            
            sv = new StudentInf(hovaten,mssv,tinChi,soHocPhan,namHoc,"Chương Trình Mẫu");
            // Them sv vao danh sach
            themSV(sv);
            HoVaTen.setText("");
            MSSV.setText("");
            NamHoc.setText("");
            TinChiDangKi.setText("");
            Warning.setText("");
            SoHocPhan.setText("");
            ChuongTrinh.setSelected(false);
        }
        else {Warning.setText("Chưa chọn hình thức đăng kí học");}
        hienThiDanhSach();
    }//GEN-LAST:event_SubmitActionPerformed
    // Ham hien thi danh sach sinh vien
    @Override
    public void hienThiDanhSach() {
        int i = 1;
        for (StudentInf sv : dssv) {
            System.out.println("Sinh vien thu " + i + " la:");
            sv.hienThiThongTin();
            i++;
        }
    }
    // Ham tim kiem sinh vien theo ten, MSSV, So Tin Chi
    @Override
    public void timKiem(String name, String MSSV,int SoTinChi) {
        DefaultTableModel TimKiem = (DefaultTableModel) QuanliSinhVien1.getModel();
        TimKiem.setNumRows(0);
        List<StudentInf> dssvTimKiem = new ArrayList<>();
        for (StudentInf sv : dssv) {
            if (name.equals(sv.getTen())&&MSSV.equals("")&&SoTinChi==0) {
                  dssvTimKiem.add(sv);
            } else if(name.equals(sv.getTen())&&MSSV.equals(sv.getMSSV())&&SoTinChi==0){
                  dssvTimKiem.add(sv);
            }else if(name.equals(sv.getTen())&&MSSV.equals("")&&SoTinChi==sv.getTinChi()){
                  dssvTimKiem.add(sv);
            } else if(name.equals(sv.getTen())&&MSSV.equals(sv.getMSSV())&&SoTinChi==sv.getTinChi()){
                dssvTimKiem.add(sv);
            } else if(name.equals("")&&MSSV.equals(sv.getMSSV())&&SoTinChi==0){
                dssvTimKiem.add(sv);
            } else if(name.equals("")&&MSSV.equals(sv.getMSSV())&&SoTinChi==sv.getTinChi()){
                dssvTimKiem.add(sv);
            } else if(name.equals("")&&MSSV.equals("")&&SoTinChi==sv.getTinChi()){
                dssvTimKiem.add(sv);
            } 
        } 
        System.out.println(dssvTimKiem.size());
         if(dssvTimKiem.size()==0){
                StudentInf svinf = new StudentInf();
                svinf.hienThiThongTin();
                TimKiem.setNumRows(0);
                ErrorTimKiem.setText("Khong Tim Thay Sinh Vien");
            }else{
             for(StudentInf sv: dssvTimKiem){
                 TimKiem.addRow(new Object[]{sv.getTen(),sv.getMSSV(),sv.getHinhThucDangKi(),sv.getSoHocPhan(),sv.getTinChi(),sv.getNamHoc(),HocPhiTinChi(sv.getTinChi())});
                 sv.hienThiThongTin();
                 ErrorTimKiem.setText("");
             }
        }
    }
    
    //None
    private void QuanliSinhVien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuanliSinhVien1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_QuanliSinhVien1MouseClicked
    
    //Ham thuc hien tim kiem du lieu nhap vao
    private void LookUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LookUpActionPerformed
       String TenLookUp = HoTenTimKiem.getText();
       String MSSVLookUp = MSSVTimKiem.getText();
       int SoTinChiLookUp = Integer.parseInt(SoTinChiTimKiem.getText());
       timKiem(TenLookUp,MSSVLookUp,SoTinChiLookUp);
    }//GEN-LAST:event_LookUpActionPerformed

    //None
    private void SoHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoHocPhanActionPerformed

    }//GEN-LAST:event_SoHocPhanActionPerformed

    //Ham cap quyen chinh sua nhung thong tin duoc yeu cau: hoc phi 1 tin chi , hoc phi 1 hoc phan, he so tin chi 1 hoc phan, phi quan li 
    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
        MotTinChi.setEditable(true);
        MotHocPhan.setEditable(true);
        HeSo.setEditable(true);
        PhiQuanLi.setEditable(true);
        CanEdit.setText("Bạn Có Thế Chỉnh Sủa Thuộc Tính Học Phí");
        CanEdit.setForeground (Color.red);
        JOptionPane.showMessageDialog(this,"Có thể cập nhật lại các phí học tập");
    }//GEN-LAST:event_Edit1ActionPerformed

    //Ham Tinh so tin chi ung voi so so hoc phan dang ki 
    private void TinhTinChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhTinChiActionPerformed
         TinChiDangKi.setEditable(true);
         int sohocphan = Integer.parseInt(SoHocPhan.getText());
         int hesotinchi =  Integer.parseInt(HeSo.getText());
         TinChiDangKi.setText(Integer.toString(sohocphan*hesotinchi));
    }//GEN-LAST:event_TinhTinChiActionPerformed

    //Ham Cap nhat cac thong tin duoc yeu cau: hoc phi 1 tin chi , hoc phi 1 hoc phan, he so tin chi 1 hoc phan, phi quan li 
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        MotTinChi.setEditable(false);
        MotHocPhan.setEditable(false);
        HeSo.setEditable(false);
        PhiQuanLi.setEditable(false);
        CanEdit.setText("");
        JOptionPane.showMessageDialog(this,"Cập nhật thành công các phí học tập");
    }//GEN-LAST:event_updateActionPerformed

    //Ham hien du lieu thong ke
    private void ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeActionPerformed
        String thoigian = TgianThongKe.getText();
        ThongKe thongke = new ThongKe(thoigian,dssv);
        //Up-casting
        ThongTinThongKe thongtin_is_null = new ThongKe();
        if (thoigian.equals("")){
//            thongtin_is_null.showError();
            //down-casting
            ((ThongKe)thongke).showError();
            errThongKe.setText("Nhap thoi gian can thong ke");
        } else{
        errThongKe.setText("");
        SoLuongSinhVien.setText(Integer.toString(thongke.getCount()));
        SoLuongSinhVienTinChi.setText(Integer.toString(thongke.getCountTinChi()));
        SoLuongSinhVienChuongTrinh.setText(Integer.toString(thongke.getCountChuongTrinh()));
        HocPhi.setText(String.valueOf(thongke.getHocPhi()));
        HocPhiTheoTinChi.setText(String.valueOf(thongke.getHocPhiTinChi()));
        HocPhiTheoChuongTrinhMau.setText(String.valueOf(thongke.getHocPhiChuongTrinh()));}
    }//GEN-LAST:event_ThongKeActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLi().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CanEdit;
    private javax.swing.JRadioButton ChuongTrinh;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Edit1;
    private javax.swing.JLabel ErrorTimKiem;
    private javax.swing.JTextField HeSo;
    private javax.swing.JTextField HoTenTimKiem;
    private javax.swing.JTextField HoVaTen;
    private javax.swing.JLabel HocPhi;
    private javax.swing.JLabel HocPhiTheoChuongTrinhMau;
    private javax.swing.JLabel HocPhiTheoTinChi;
    private javax.swing.JButton LookUp;
    private javax.swing.JTextField MSSV;
    private javax.swing.JTextField MSSVTimKiem;
    private javax.swing.JTextField MotHocPhan;
    private javax.swing.JTextField MotTinChi;
    private javax.swing.JTextField NamHoc;
    private javax.swing.JTextField PhiQuanLi;
    private javax.swing.JTable QuanliInhVien;
    private javax.swing.JTable QuanliSinhVien1;
    private javax.swing.JTextField SoHocPhan;
    private javax.swing.JLabel SoLuongSinhVien;
    private javax.swing.JLabel SoLuongSinhVienChuongTrinh;
    private javax.swing.JLabel SoLuongSinhVienTinChi;
    private javax.swing.JTextField SoTinChiTimKiem;
    private javax.swing.JButton Submit;
    private javax.swing.JTextField TgianThongKe;
    private javax.swing.JButton ThongKe;
    private javax.swing.JRadioButton TinChi;
    private javax.swing.JTextField TinChiDangKi;
    private javax.swing.JButton TinhTinChi;
    private javax.swing.JLabel Warning;
    private javax.swing.JLabel errThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables



}
